language: php

php:
  - 5.5
  - 7.1

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit

notifications:
  email:
    on_success: never
    on_failure: always

branches:
  except:
    - /^\d+\.\d+\.\d+/